Repository corail-research/SeaPearl.jl, pull requests merged in 2021-05, with the labels that each got.

#115 Feature/alldifferent
  src/CP/constraints/algorithms/matching.jl
  src/CP/constraints/alldifferent.jl
  src/CP/constraints/constraints.jl
  test/CP/constraints/algorithms/matching.jl
  test/CP/constraints/alldifferent.jl
  test/CP/constraints/constraints.jl
Labels: enhancement

#117 Fix for Absolute.jl
  src/CP/constraints/absolute.jl
  test/CP/constraints/absolute.jl
  test/CP/constraints/constraints.jl
Labels: bug

#121 SeaPearl cleanup and bug fix for RL value selection
  .gitignore
  Project.toml
  assets/RL_SeaPearl.drawio
  assets/RL_SeaPearl.png
  examples/learning_cp/coloring/ilancoloring.jl
  examples/learning_cp/knapsack/ilanknapsack.jl
  src/CP/valueselection/lh_utils.jl
  src/RL/RL.jl
  src/RL/explorer/cp_explorer.jl
  src/RL/explorer/directed_explorer.jl
  src/RL/learners/cpdqn.jl
  src/RL/nn_structures/fixed_output_gat.jl
  src/RL/nn_structures/fixed_output_gcn.jl
  src/RL/nn_structures/flexGNN.jl
  src/RL/nn_structures/nn_structures.jl
  src/RL/nn_structures/variable_output_gcn_lstm.jl
  src/RL/nn_structures/weighted_graph_gat.jl
  src/RL/representation/default/cp_layer/rendering.jl
  src/RL/representation/default/defaultstaterepresentation.jl
  src/datagen/knapsack.jl
  src/experiment/launch_experiment.jl
  src/experiment/training.jl
  test/CP/valueselection/lh_utils.jl
  test/RL/explorers/directed_explorer.jl
  test/RL/nn_structures/fixed_output_gcn.jl
  test/RL/nn_structures/nn_structures.jl
  test/datagen/tsptw.jl
  test/runtests.jl
Labels: bug, documentation

#119 Table constraint: compact table
  src/CP/constraints/algorithms/rsparsebitset.jl
  src/CP/constraints/compacttable.jl
  src/CP/constraints/constraints.jl
  src/CP/core/fixPoint.jl
  src/CP/core/search/dfs.jl
  test/CP/constraints/algorithms/rsparsebitset.jl
  test/CP/constraints/compacttable.jl
  test/CP/constraints/constraints.jl
Labels: enhancement

#130 a prettier SeaPearl
  src/CP/constraints/binarymaximum.jl
  src/CP/constraints/binaryor.jl
  src/CP/constraints/compacttable.jl
  src/CP/constraints/element2d.jl
  src/CP/constraints/equal.jl
  src/CP/constraints/greaterorequal.jl
  src/CP/constraints/inset.jl
  src/CP/constraints/interval.jl
  src/CP/constraints/isbinaryor.jl
  src/CP/constraints/islessorequal.jl
  src/CP/constraints/lessorequal.jl
  src/CP/constraints/notequal.jl
  src/CP/constraints/reifiedinset.jl
  src/CP/constraints/setdiffsingleton.jl
  src/CP/constraints/setequalconstant.jl
  src/CP/constraints/sumgreaterthan.jl
  src/CP/constraints/sumlessthan.jl
  src/CP/constraints/sumtozero.jl
  src/CP/variables/BoolDomain.jl
  src/CP/variables/BoolVar.jl
  src/CP/variables/IntDomain.jl
  src/CP/variables/IntSetDomain.jl
  src/CP/variables/IntSetVar.jl
  src/CP/variables/IntVar.jl
Labels: enhancement

#129 fix: SetDiffSingleton propagation
  src/CP/constraints/setdiffsingleton.jl
Labels: bug

#131 Removed extra dependencies
  Project.toml
Labels: invalid

#138 Compact Table optimization
  src/CP/constraints/compacttable.jl
  test/CP/constraints/compacttable.jl
Labels: enhancement

#140 CPModification upgrade
  src/CP/constraints/absolute.jl
  src/CP/constraints/alldifferent.jl
  src/CP/constraints/binarymaximum.jl
  src/CP/constraints/compacttable.jl
  src/CP/constraints/inset.jl
  src/CP/constraints/islessorequal.jl
  src/CP/constraints/reifiedinset.jl
  src/CP/constraints/setdiffsingleton.jl
  src/CP/constraints/setequalconstant.jl
  src/CP/constraints/sumgreaterthan.jl
  src/CP/constraints/sumlessthan.jl
  src/CP/core/model.jl
  src/CP/variables/IntSetDomain.jl
  src/CP/variables/IntSetVar.jl
  test/CP/CP.jl
  test/CP/constraints/absolute.jl
  test/CP/constraints/compacttable.jl
  test/CP/constraints/setdiffsingleton.jl
  test/CP/core/cpModification.jl
Labels: bug, enhancement

#141 Entire refacto of search metrics
  Project.toml
  README.md
  src/CP/core/model.jl
  src/CP/core/search/search.jl
  src/MOI_wrapper/MOI_wrapper.jl
  src/MOI_wrapper/homemade_bridging.jl
  src/MOI_wrapper/optimizer_accessors.jl
  src/RL/utils.jl
  src/SeaPearl.jl
  src/datagen/coloring.jl
  src/datagen/knapsack.jl
  src/datagen/tsptw.jl
  src/experiment/benchmark_solving.jl
  src/experiment/evaluation.jl
  src/experiment/experiment.jl
  src/experiment/launch_experiment.jl
  src/experiment/metrics/basicmetrics.jl
  src/experiment/metrics/metrics.jl
  src/experiment/training.jl
  test/CP/constraints/alldifferent.jl
  test/CP/constraints/compacttable.jl
  test/CP/constraints/disjunctive.jl
  test/CP/core/model.jl
  test/CP/core/search/dfs.jl
  test/CP/core/search/ilds.jl
  test/CP/variableselection/mindomain.jl
  test/CP/variableselection/random.jl
  test/datagen/tsptw.jl
  test/experiment/basicmetrics.jl
  test/experiment/evaluation.jl
  test/experiment/experiment.jl
  test/experiment/training.jl
  test/runtests.jl
Labels: enhancement
